name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

env:
  PYATS_UNAME: ${{ secrets.DEVICE_USERNAME}}
  PYATS_PWORD: ${{ secrets.DEVICE_PASSWORD}}

jobs:
  code-quality:
    name: "code-quality"
    strategy:
      matrix:
        python-version: [3.8.6]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        env:
          AGENT_TOOLSDIRECTORY: ${{ runner.tool_cache }}
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      - name: Run black
        run: black . --check
      - name: Run isort
        run: isort . --check-only --profile black
      - name: Run autoflake
        run: autoflake -r . --expand-star-imports --remove-unused-variables --remove-all-unused-imports
      - name: Run bandit
        run: bandit -r .
      - name: Run flake8
        run: flake8 . --ignore=E501
      - name: Run pydocstyle
        run: pydocstyle .
      - name: Run yamllint
        run: yamllint .
      - name: Run mypy
        run: mypy .
  test:
    name: test
    strategy:
      matrix:
        python-version: [3.8.6]
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        env:
          AGENT_TOOLSDIRECTORY: ${{ runner.tool_cache }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m pytest -vv --tb=short tests
